<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <main>
        <h1>Liste des clients</h1>
        <p>Client N°<?= $myCustomer['customerNumber']; ?> : <?= $myCustomer['customerName']; ?></p>
        <ul>
            <?php foreach($customers as $customer): ?>
            
            <li><?= $customer['customerName']; ?></li>
            
            <?php endforeach; ?>
        </ul>
    </main>
</body>
</html>