<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Modification d'un chien</h1>
    <form action="update.php" method="POST">
        <input type="hidden" name="dogId" value="<?= $chien['Id']; ?>">
        <input type="text" name="dogName" value="<?= $chien['nom']; ?>" placeholder="Entrez le nom du chien" required>
        <input type="text" name="dogRace" value="<?= $chien['race']; ?>" placeholder="Indiquez la race du chien" required>
        <input type="number" name="dogAge" value="<?= $chien['age']; ?>" placeholder="Indiquez l'âge du chien" min="1" required>
        <select name="dogVaccination" required>
            <option value="">Vaccination</option>
            <option value="1" <?php if($chien['vaccination'] == 1) : ?>selected<?php endif ?>>Oui</option>
            <option value="0" <?php if($chien['vaccination'] == 0) : ?>selected<?php endif ?>>Non</option>
        </select>
        <input type="url" name="dogPhoto" value="<?= $chien['photo']; ?>" placeholder="Entrez l'url de la photo" required>
        <button type="submit">Enregistrer</button>
    </form>
</body>
</html>