<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Traducteur FR-ANG</title>
</head>
<body>
    <header>
     <h1>Traducteur Français-Anglais</h1>   
    </header>
    <main>
    <form action="index.php" method="POST">
            <ul>
                <li>
                    <label for="word">Mot :</label>
                    <input type="text" id="word" name="word">
                 </li>
                 <li>
                    <label for="direction">Sens de traduction :</label>
                    <select id="direction" name="direction">
                        <option value="toEnglish">Français vers Anglais</option>
                        <option value="toFrench">Anglais vers Français</option>
                    </select>
                </li>
                <li>
                   <input type="submit" value="Traduire"> 
                </li>
            </ul>
    </form>
    <!-- Est-ce que la variable $message est définie et est-ce que sa valeur est non nulle ? -->
    <?php if(isset($message)): ?>
    
        <p><?php echo $message; ?></p>
    
    <?php endif; ?>
    </main>
</body>
</html>