<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="order-form.css">
</head>
<body>
    <section>
        <h1>Détail de la commande n° <?= $_GET['orderNumber']; ?></h1>
        
        <article class="order-form-customer">
            <h2><?= $customer['customerName'] ?></h2>
            <h3><?= $customer['contactLastName'] ?> <?= $customer['contactFirstName'] ?></h3>
            <p><?= $customer['addressLine1'] ?></p>
            <p><?= $customer['addressLine2'] ?></p>
            <p><?= $customer['city'] ?></p>
        </article>
        <hr>
        <table class="standard-table">
            <caption>Commande n° <?= $_GET['orderNumber']; ?></caption>
            <thead>
                <tr>
                    <th>Nom du produit</th>
                    <th>Prix unitaire</th>
                    <th>Quantité</th>
                    <th>Sous-total</th>
                </tr>
            </thead>
            <!-- le tfoot tjrs avant le tbody -->
            <tfoot>
                <tr>
                    <th colspan="3">Montant Total HT</th>
                    <th><?= number_format($totalAmount, 2); ?> $</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %)</th>
                    <th><?= number_format($totalAmount * 0.20, 2); ?></th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC</th>
                    <!-- Multiplier par 1.20 revient à ajouter 20% à une variable -->
                    <th><?= number_format($totalAmount * 1.20, 2); ?> $</th>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach($orderDetails as $orderLine): ?>
                <!-- Pour chaque case du tab orderDetails -->
                    <tr>
                        <td><?= $orderLine['productName']; ?></td>
                        <td><?= number_format($orderLine['priceEach'], 2); ?> $</td>
                        <!-- le nbre qu'on veut afficher puis le nbre de chiffres après la virgule -->
                        <td><?= $orderLine['quantityOrdered']; ?></td>
                        <td><?= number_format($orderLine['totalPrice'], 2); ?> $</td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>
</body>
</html>    