<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Découverte du PHP</title>
</head>
<body>
    <header>
        
    </header>
    <main>
        <section class="solution container">
          <h1><?php echo 'Bonjour PHP !'; ?></h1>  <!-- ou importer du php comme en dessous -->
          <h1><?php echo $title; ?></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione quis accusantium, earum error laborum vitae placeat, voluptas voluptatem molestias, aspernatur distinctio dolor dolores repellendus praesentium adipisci totam quos cum. Eum debitis autem, sequi, quam, consequatur eligendi ad modi dolores repellendus ipsum sapiente placeat? Consequuntur blanditiis in odio laborum quam, cupiditate voluptatem culpa ipsum ut laudantium, rem dolorem nihil, quos doloribus est dolores harum minima eligendi! Harum laudantium obcaecati nihil saepe.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat alias, eos est eveniet mollitia a sunt iusto tempore molestiae dicta sequi pariatur illum voluptates repudiandae quidem excepturi natus aliquam. Dolorum!</p>
        </section>
    </main>
    <footer>
        
    </footer>
    
</body>
</html>