<!-- Le haut des pages -->
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>liste d'articles</title>
    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
    <link rel="stylesheet" href="#">
    
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
    
    <!-- En-tête de la page -->
    <header>
       <!-- Navigation -->
        <nav>
            <a href="admin.php"><i class="fa fa-cogs"></i> Tableau de bord</a>
        </nav> 
    </header>
    
    
    <!-- Corps de la page -->
    <main>
        <?php include 'views/' . $template . '.phtml'; ?>
    </main>


    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
    
    <script src="js/main.js"></script>
</body>
</html>    